import { ENV } from './config/env';

export const environment = {
  production: true,
  APP_DEMO: ENV.STEEM_DEMO_ENABLE,
  APP_HOST: ENV.APP_HOST,
  API_HOST: ENV.STEEMSAYS_API_HOST,
  CHAR_LIMIT: ENV.CHAR_LIMIT,
  PRIMARY_TAG: ENV.PRIMARY_TAG,
  STEEMIT_IMAGE_URL: ENV.STEEMIT_IMAGES_URL,
  TREND_TAGS_LIMIT: ENV.TREND_TAGS_LIMIT,
  TO_FOLLOW_LIMIT: ENV.TO_FOLLOW_LIMIT,
  POPOVER_FOLLOWER_LIMIT: ENV.POPOVER_FOLLOWER_LIMIT,
  STEEM_DEMO_PASS: ENV.STEEM_DEMO_PASS,
  SOCKET_URL: ENV.SOCKET_URL
};
